language: go
go:
  - 1.5
go_import_path: gopkg.in/mwmahlberg/pkv.v1
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/pierrre/gotestcover
install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get -u "github.com/spf13/cobra"
script:
  - "$HOME/gopath/bin/gotestcover -v -covermode=count -coverprofile=coverage.out ./internal"
  - "$HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out"

